### ISSUE TITLE
NuGet package for controls

### ISSUE THREAD

**Issue by rappen** [jamesnovak/Futurez.XrmToolbox.Controls#1]
Similar to the [CRMWinForm](https://www.nuget.org/packages/Cinteros.Xrm.CRMWinForm/) package it would be nice to be able to include the controls by adding a NuGet package to my project.

**Comment by jamesnovak** [comment]
@rappen 
Can you give this one a try?  Working on the How To document now!  Works with my current set up of Visual Studio 2017.  I will be testing it on a clean machine next;
https://www.nuget.org/packages/Futurez.XrmToolbox.Controls/
